#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi


#
# alias
#
alias p2='pyenv shell 2.7.15'
alias gs='git status'
alias curl_header='curl -D - -s -o /dev/null'
alias curl_time='curl -o /dev/null -s -w  "Connect: %{time_connect} TTFB: %{time_starttransfer} Total time: %{time_total} \n"'
alias getip='curl ifconfig.me'
alias getip-all='curl ifconfig.me/all'
alias getip-json='curl ifconfig.me/all.json'

alias flutter-dev-tool='flutter packages pub global run devtools'
alias f='cd ~/Documents/Projects/firechat'


#
# path
#

export PDIR=~/Documents/Projects
export PATH=~/.scala-2.12.6/bin:$PATH

export PATH=/usr/local/Cellar/git/2.14.1/bin:$PATH
eval "$(pyenv init -)"

export PATH=$PATH:/usr/local/opt/go/libexec/bin
export GOPATH=~/.golang

export QT_DIR=~/.Qt
export CGO_CXXFLAGS_ALLOW=".*" 
export CGO_LDFLAGS_ALLOW=".*" 
export CGO_CFLAGS_ALLOW=".*" 
export QT_HOMEBREW=true


export PATH=~/.nodebrew/current/bin:$PATH
export PATH=~/.gcloud/bin:$PATH

# Use Java8
# export JAVA_HOME=`/System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/java_home -v "1.8"`
# PATH=${JAVA_HOME}/bin:${PATH}

export ANDROID_HOME=~/Library/Android/sdk
export ANDROID_SDK_ROOT=/Users/tsubasa/Library/Android/sdk
export PATH=~/.android-sdk/bin:$PATH

export PATH=~/.flutter_tool/bin:$PATH

