#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# TMUX を起動する。ログインシェルでのみ実行されるので分岐はいらないかも
while [[ ! -n $TMUX ]]; do
  if [[ ! -n "$(command -v tmux)" ]]; then
    echo "TMUX is not installed. Starting terminal normally."
    break
  fi
  if [[ ! -n "$(command -v fzf)" ]]; then
    tmux > /dev/null 2>&1
  fi
  # get the IDs
  ID="`tmux list-sessions 2>/dev/null`"
  if [[ ! -z "$ID" ]]; then
    ID="$ID\n"
  fi
  fzf_header="Select or create a tmux session. Ctrl-c to continue without tmux."
  create_new_session="Create New Session"
  ID="$ID${create_new_session}:"
  ID="`echo $ID | fzf --height 50% --tac --header $fzf_header | cut -d: -f1`"
  if [[ "$ID" = "${create_new_session}" ]]; then
    tmux new-session > /dev/null 2>&1
  elif [[ -n "$ID" ]]; then
    tmux attach-session -t "$ID" > /dev/null 2>&1
  else
    break  # Start terminal normally
  fi
done


