#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

# functions 以下の関数を遅延読み込み
fpath=(
    "$HOME/.dotfiles/zsh/functions"
    $fpath
)
autoload -U $(ls -1 "$HOME/.dotfiles/zsh/functions")

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi


#
# alias
#
alias_open_with_app() {
    [ -e "$2" ] && alias $1="open -a '$2'"
}

alias dc='docker compose'
alias gs='git status'
alias gc='git commit'
alias gr='cd "$(git rev-parse --show-toplevel)"'
alias curl_header='curl -D - -s -o /dev/null'
alias curl_time='curl -o /dev/null -s -w  "Connect: %{time_connect} TTFB: %{time_starttransfer} Total time: %{time_total} \n"'
alias getip='curl ifconfig.me'
alias getip-all='curl ifconfig.me/all'
alias getip-json='curl ifconfig.me/all.json'
alias tu='timer -s -u'

alias compress-pdf='command gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer -dNOPAUSE -dQUIET -dBATCH -sOutputFile=output.pdf'
alias flutter-dev-tool='flutter packages pub global run devtools'
alias_open_with_app idea "/Applications/IntelliJ IDEA.app"
alias_open_with_app pycharm "/Applications/Pycharm.app"
alias_open_with_app clion "/Applications/Clion.app"
alias_open_with_app slack "/Applications/Slack.app"

alias t1='timer -s 1m && ringtone'
alias t2='timer -s 2m && ringtone'
alias t3='timer -s 3m && ringtone'
alias t4='timer -s 4m && ringtone'
alias t5='timer -s 5m && ringtone'
alias t6='timer -s 6m && ringtone'
alias t7='timer -s 7m && ringtone'
alias t8='timer -s 8m && ringtone'
alias t9='timer -s 9m && ringtone'
alias t10='timer -s 10m && ringtone'

setopt nonomatch

# Auto suggestions of command
source ~/.dotfiles/zsh/zsh-autosuggestions.zsh

# fzf completion
source ~/.dotfiles/zsh/fzf-completion.zsh
source ~/.dotfiles/zsh/fzf-key-bindings.zsh
export FZF_COMPLETION_TRIGGER='**'
export FZF_DEFAULT_COMMAND='ls -a -1'


# keybind
# bind ^L^L clear and tmux clear
function _clear() { clear; [[ -n "$TMUX" ]] && tmux clear; zle reset-prompt; }
zle -N _clear
bindkey "^L^L" _clear

# スペースで区切られた単語を移動
bindkey "^S" vi-backward-blank-word
bindkey "^F" vi-forward-blank-word

bindkey "^V" edit-command-line

# Completion
if [ -n "$(command -v kubectl)" ]; then
    source <(kubectl completion zsh)
fi
if [ -e "$HOME/.gcloud/completion.zsh.inc" ]; then
    source "$HOME/.gcloud/completion.zsh.inc"
fi


# rbenv
export PATH="$PATH:$HOME/.rbenv/bin"
if [ -n "$(command -v rbenv)" ]; then
  eval "$(rbenv init -)"
fi

# direnv

if [ -n "$(command -v direnv)" ]; then
    eval "$(direnv hook zsh)"
fi

# Pyenv init must be excutated after setting PATH
if [ -n "$(command -v pyenv)" ]; then
  eval "$(pyenv init --path)"
  eval "$(pyenv init - --no-rehash)"
fi

# Rbenv
if [ -n "$(command -v rbenv)" ]; then
    eval "$(rbenv init - zsh)"
fi

# Nodenv
if [ -n "$(command -v nodenv)" ]; then
    eval "$(nodenv init -)"
fi

if command -v brew > /dev/null; then
    source $(brew --prefix asdf)/libexec/asdf.sh
fi

# zsh-syntax-highlighting must be after all zle modules
source ~/.dotfiles/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


